v1.0.0 - minor changes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -27,10 +27,10 @@ fi
 
 if [[ $version == v* ]]; then
   version=${version:1}
-  if [[ $version == 0.* ]]; then
-    echo "Error: Version $version is not supported"
-    exit 1
-  fi
+fi
+if [[ $version == 0.* ]]; then
+  echo "Error: Version $version is not supported"
+  exit 1
 fi
 
 if [ "$macOS" = true ]; then
