Enhanced scripts - 2.0.1

diff --git a/scripts/comment-check b/scripts/comment-check
--- a/scripts/comment-check
+++ b/scripts/comment-check
@@ -1,3 +1,9 @@
 #!/bin/bash
 
 python scripts/py/check_comment.py
+
+if [ $? -ne 0 ]; then
+    echo "❌ Code comment check failed. Please ensure all public items have appropriate comments."
+    exit 1
+fi
+echo "✅ Code comment check passed."
diff --git a/scripts/format-check b/scripts/format-check
--- a/scripts/format-check
+++ b/scripts/format-check
@@ -4,3 +4,9 @@ rustup component add rustfmt > /dev/null 2>&1
 
 cargo fmt --version
 cargo fmt --all -- --check
+
+if [ $? -ne 0 ]; then
+    echo "❌ Code formatting check failed. Please run 'cargo fmt' to format the code."
+    exit 1
+fi
+echo "✅ Code format check passed."
diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -3,3 +3,9 @@
 rustup component add clippy  > /dev/null 2>&1
 cargo clippy --version
 cargo clippy -- -D warnings
+
+if [ $? -ne 0 ]; then
+    echo "❌ Linting failed. Please fix the above issues."
+    exit 1
+fi
+echo "✅ Linting passed."
diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,3 +1,9 @@
 #!/bin/bash
 
 cargo test -- --test-threads=1 --nocapture
+
+if [ $? -ne 0 ]; then
+    echo "❌ Tests failed. Please fix the above issues."
+    exit 1
+fi
+echo "✅ All tests passed."
